<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.1.13 setup script
 * Date: Fri, 11 Jul 2014 11:58:45 +0400
 */

/* Servers configuration */
$i = 0;

/* Server: u301331.mysql.masterhost.ru [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'u301331.mysql.masterhost.ru';
$cfg['Servers'][$i]['host'] = 'u301331.mysql.masterhost.ru';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'u301331';
$cfg['Servers'][$i]['password'] = '39dshotrygl';

/* End of servers configuration */

$cfg['blowfish_secret'] = '53bf991b1f3af5.19524770';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>